---
title: "Covid Dashboard"
author: "Kellin, Valerie, Sophia, Beth"
date: "11/30/2020"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
---

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(viridis)
library(tigris)
library(ggthemes)
library(quantmod)
library(flexdashboard)
library(dygraphs)
library(readr)
library(readxl)
library(lubridate)


```


## Time Series Plot


```{r}
penn_state <- read_excel("PennStateCovidTables_new.xlsx")
penn_cases <- penn_state %>%
  mutate(Week = week(Week)) %>%
  select(Week, Total_Positive) %>%
  rename(Positive = Total_Positive)

dygraph(penn_cases[,1:2], group = "cases") %>% 
  dySeries(c("Positive"), label = "Penn State")

osu <- read_excel("Ohio State COVID-19 Dashboard Data Tables.xlsx", skip = 5)
osu_cases <- osu %>%
  select(`Test Date`, `Positive Tests...9`) %>%
  rename(Week = `Test Date`, 
         Positive = `Positive Tests...9`) %>%
  mutate(Week = week(Week)) %>%
  group_by(Week) %>%
  summarise(sum(Positive))

dygraph(osu_cases[,1:2], group = "cases") %>% 
  dySeries(c("sum(Positive)"), label = "Ohio State")

clemson <- read_excel("clemsonDashboard.xlsx", sheet = "Daily Data") 

clemson_cases <- clemson %>%
  select(Date, Positive) %>%
  mutate(Date = week(Date)) %>%
  group_by(Date) %>%
  summarise(sum(Positive)) %>%
  slice(1:10) %>%
  rename(Week = Date)

dygraph(clemson_cases[,1:2], group = "cases") %>% 
  dySeries(c("sum(Positive)"), label = "Clemson")


u_of_g <- read_excel("UG_covid_data.xlsx")

ug_cases <- u_of_g %>%
  mutate(Week = week(`Reporting Week`)) %>%
  rename(Positive = `Total Number of Positive Student Tests*`) %>%
  mutate(College = "UG") %>%
  select(Positive:College)

dygraph(ug_cases[,1:2], group = "cases") %>% 
  dySeries(c("Positive"), label = "University of Georgia")

uf <- read_excel("UF_covid_data.xlsx")

uf_cases <- uf %>%
  mutate(Week = week(Week)) %>%
  mutate(College = "UF")

dygraph(uf_cases[,1:2], group = "cases") %>% 
  dySeries(c("Positive"), label = "University of Florida")
```









## South Carolina County Plot

```{r}
sc_county <- counties(state = "SC", cb = TRUE, class = "sf")

county_data <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/live/us-counties.csv")

sc_counties <- county_data %>%
  filter(state == "South Carolina") %>%
  select(date:deaths) %>% 
  group_by(fips) %>% 
  ungroup()

sc_fips <- sc_county %>% 
  mutate(fips = paste0(STATEFP, COUNTYFP)) %>% 
  full_join(sc_counties, by = "fips") 


ggplot() + 
  geom_sf(data = sc_fips, aes(fill = cases)) +
  scale_fill_viridis() +
  labs(fill = "Number of cases\n per county\n") +
  theme_tufte() +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank()) +
  ggtitle("Total Number of South Carolina Cases by County")

```






## Interactive Map Plot

# data cleaned for the map
```{r datamap}
college_raw <- 
  read_csv(
    "https://raw.githubusercontent.com/nytimes/covid-19-data/master/colleges/colleges.csv")

state_names <- read_csv("csvData_state_names.csv")
colnames(state_names)


college_raw <- college_raw %>%
  semi_join(y = state_names, 
            by = c("state" = "State"))
### Beth
#top 5 schools with highest cases for time series data, include reference point
#of when school started

top_5_overall <- college_raw %>%
  select(state, county, city, college, cases) %>%
  group_by(state) %>%
  arrange(desc(cases)) %>%
  head(10)

top5_by_state <- college_raw %>%
  select(state, county, city, college, cases) %>%
  group_by(state) %>%
  arrange(state, -cases) %>%
  slice_head(n = 10)

# Adding lat/long to each college to map into flexdashboard

city_location <- read_csv("uscities.csv") %>%
  rename(state = "state_name",
         county = "county_name")

college_location <- top5_by_state %>%
  left_join(y = city_location,
            by = c("city", "state"))

college_location <- college_location %>%
  select(state:city_ascii, state_id:county_fips, lat:lng)

geo_code <- read_excel("EDGE_GEOCODE_POSTSEC_1920.xlsx")

geo_code <- geo_code %>%
  select(NAME, CITY, STATE, LAT, LON)

college_location <- college_location %>%
  left_join(y = geo_code,
            by = c("college" = "NAME"))

college_location <- college_location %>%
  unite(col = latitude,
        c(lat, LAT),
        na.rm = TRUE) %>%
  separate(col = latitude,
           into = c("lat_1", "lat_del"),
           sep = "_")

college_location <- college_location %>%
  unite(col = longitude,
        c(lng, LON),
        na.rm = TRUE) %>%
  separate(col = longitude,
           into = c("long_1", "long_del"),
           sep = "_")

college_location_final <- college_location %>%
  select(state:cases, state_id:lat_1, long_1)

college_location_final$lat <- as.numeric(college_location_final$lat_1)
college_location_final$long <- as.numeric(college_location_final$long_1)


# add college enrollment size for rate. 

admission <- read_excel("college_admission.xlsx")

college_location <- college_location %>%
  left_join(y = admission,
            by = c("college" = "School Name"))

admission2 <- read_excel("college_enrollement.xlsx")

admission2 <- admission2 %>%
  rename(school = `School Name `)
 
college_location <- college_location %>%
  left_join(y = admission2,
            by = c("college" = "school"))

admission3 <- read_excel("top_10_enrollment.xlsx", skip = 1)

college_location <- college_location %>%
  left_join(y = admission3,
            by = c("college" = "University"))

college_location <- college_location %>%
  select(state, county.x, city, college, cases, state_id, county_fips,
         lat_1, long_1, `Total Enrollment `, Enrollment) %>%
  mutate(rate = cases/`Total Enrollment `) %>%
  write_delim(file = "college_location", delim = ",", col_names = TRUE)

```
# map code

```{r}

college_location_final$cases_type <- ifelse(college_location_final$cases <= 100, "low", ifelse(college_location_final$cases <= 500, "moderate", ifelse(college_location_final$cases > 500, "severe", "NA")))

ui <- fluidPage(
  mainPanel( 
#this will create a space for us to display our map
leafletOutput(outputId = "mymap"), 
#this allows me to put the checkmarks ontop of the map to allow people to view earthquake depth or overlay a heatmap
absolutePanel(top = 60, left = 20, 
      checkboxInput("markers", "College", FALSE),
      checkboxInput("heat", "Rank", FALSE)
    )
))

server <- function(input, output, session) {
#define the color pallate for the magnitidue of the earthquake
 pal <- colorNumeric(
    palette = c('gold', 'orange', 'dark orange', 'orange red', 'red', 'dark red'),
    domain = college_location_final$cases)
  
#define the color of for the depth of the earquakes
 pal2 <- colorFactor(
    palette = c('blue', 'yellow', 'red'),
    domain = college_location_final$cases_type
  )
 
 #create the map
  output$mymap <- renderLeaflet({
    leaflet(college_location_final) %>% 
      setView(lng = -99, lat = 45, zoom = 4)  %>% #setting the view over ~ center of North America
      addTiles() %>% 
      addCircles(data = college_location_final, lat = ~ college_location_final$lat, lng = ~ college_location_final$long, weight = 1, radius = ~sqrt(cases)*1000, popup = ~as.character(cases), label = ~as.character(paste0("Cases: ", sep = " ", cases, sep = " ", "College: ", sep = " ", college, sep =" ", "County: ", sep = " ", county.x)), color = ~pal(cases), fillOpacity = 0.5)
  })
  
  #next we use the observe function to make the checkboxes dynamic. If you leave this part out you will see that the checkboxes, when clicked on the first time, display our filters...But if you then uncheck them they stay on. So we need to tell the server to update the map when the checkboxes are unchecked.
  observe({
    proxy <- leafletProxy("mymap", data = college_location_final)
    proxy %>% clearMarkers()
    if (input$markers) {
      proxy %>% addCircleMarkers(stroke = FALSE, color = ~pal2(cases_type),
                                 fillOpacity = 0.2, 
                                 label = ~as.character(paste0("College: ", 
                                                              sep = " ", college))) %>%
        addLegend("bottomright", pal = pal2, values = college_location_final$cases_type,
                  title = "Case Type",
                  opacity = 1)}
    else {
      proxy %>% clearMarkers() %>% clearControls()
    }
  })
  
  observe({
    proxy <- leafletProxy("mymap", data = college_location_final)
    proxy %>% clearMarkers()
    if (input$heat) {
      proxy %>%  addHeatmap(lng=~long, lat=~lat, intensity = ~cases, blur =  10, max = 0.05, radius = 15) 
      }
    else{
      proxy %>% clearHeatmap()
      }
    
    
  })
  
}

shinyApp(ui, server)




```




## Blurb Color Spot

```{r}

```



